# This is a basic workflow to help you get started with Actions

name: Make SealOsBootAnimation.zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/system/product/media/BOOTANIMATION
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         zip -0 -r SealOsBootAnimation.zip
      - uses: actions/upload-artifact@v3
        with:
          name: SealOsBootAnimation.zip
          path: ${{ github.workspace }}/system/product/media/SealOsBootAnimation.zip
