name: GitHub Actions Demo
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create ankiaddon
        run: zip -r -q folder.zip BOOTANIMATION
