name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
      - name: zip
        run: |
        zip -0 -r SealOsBootAnimation.zip /system/product/media/BOOTANIAMATION
      - uses: actions/upload-artifact@v1
        with:
          name: SealOsBootAnimation 
          path: ${{ github.workspace }}/SealOsBootAnimation.zip
