name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: system/product/media/BOOTANIMATION/ 
          dest: result.zip
