name: Zip Files

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
     - uses: actions/checkout@v3
          with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'TOBY19k/Seal-Os-Boot-Animation-Installer'
      - run: ${{ github.workspace }}/zip.sh
      - uses: actions/upload-artifact@v3
        with:
          name: SealOsBootAnimation 
          path: ${{ github.workspace }}/SealOsBootAnimation.zip
