name: Make Seal Os Boot Animation Installer

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/system/product/media/BOOTANIMATION 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Zip boot animation 
        run: |
          zip -0 -r bootanimation.zip part0 part1 part2 desc.txt sealos.txt
          mv bootanimation.zip ${{ github.workspace }}/system/product/media/SealOsBootAnimation.zip
      - name: Delete file & folder that we don't want in the flash file
        run: |
          rm ${{ github.workspace }}/system/addon.d/addon.d.md
          rm -r ${{ github.workspace }}/system/product/media/BOOTANIMATION
      - uses: actions/upload-artifact@v3
        with:
          name: SealOsBootAnimationInstaller
          path: |
            /${{ github.workspace }}/system
            /${{ github.workspace }}/META-INF
