name: Make Release

# Controls when the workflow will run
on:
  # Triggers the workflow on tag push
  push:
    tags: '*'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/system/product/media/BOOTANIMATION 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Zip boot animation 
        run: |
          zip -0 -r ${{ github.workspace }}/system/product/media/SealOsBootAnimation.zip part0 part1 part2 desc.txt sealos.txt
      - name: Delete file & folder that we don't want in the flash file
        run: |
          rm ${{ github.workspace }}/system/addon.d/addon.d.md
          rm -r ${{ github.workspace }}/system/product/media/BOOTANIMATION
      - name: Upload Seal Os Boot Animation Installer
        uses: actions/upload-artifact@v3
        with:
          name: SealOsBootAnimationInstaller
          path: |
            /${{ github.workspace }}/system
            /${{ github.workspace }}/META-INF
      - name: Zip Seal Os Boot Animation Installer 
        run: |
          zip -r SealOsBootAnimationInstaller.zip system META-INF
        working-directory: ${{ github.workspace }}/
      - name: Publish release Zip 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ${{ github.workspace }}/SealOsBootAnimationInstaller.zip
