name: Make Release

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Zip boot animation 
        run: |
          zip -0qry -i \*.txt \*.png @ ${{ github.workspace }}/system/media/SealOsBootAnimation.zip *.txt part*
        working-directory: ${{ github.workspace }}/system/media/BOOTANIMATION 
      - name: Delete file & folder that we don't want in the flash file
        run: |
          rm system/addon.d/addon.d.md
          rm -r system/media/BOOTANIMATION
      - name: Upload Seal Os Boot Animation Installer
        uses: actions/upload-artifact@v3
        with:
          name: SealOsBootAnimationInstaller
          path: |
            /${{ github.workspace }}/system
            /${{ github.workspace }}/META-INF
      - name: Zip Seal Os Boot Animation Installer 
        run: |
          zip -r SealOsBootAnimationInstaller.zip system META-INF
      - name: Publish release Zip 
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'V1.1.0'
          release_name: 'V1.1.0'
          body_path: '.github/ReleaseNotes.md'
          prerelease: false
          draft: false
          asset_files: '${{ github.workspace }}/SealOsBootAnimationInstaller.zip'
