name: Make Test Zip

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Delete files that we don't want in the flash file
        run: |
          rm system/addon.d/addon.d.md
          rm system/media/BOOTANIMATION/BOOTANIMATION.md
      - name: Upload Seal Os Boot Animation Installer
        usv3
        with:
          name: SealOsBootAnimationInstallerTest
          path: |
            /${{ github.workspace }}/system
            /${{ github.workspace }}/META-INF
