name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '/product/media/release.zip'
        directory: 'system'
        path: '/product/media/BOOTANIAMATION'
        exclusions: '*.git* /*node_modules/* .editorconfig'
